project: 
  type: website
  output-dir: docs

website:
  title: "My Data Analysis Portfolio"
  navbar:
    left:
      - text: "About Me"
        href: ./aboutme.html
      - text: "Projects"
        menu:
          - text: "R Coding Exercise"
            href: ./coding_exercise.html
          - text: "Visualization Exercise"
            href: ./visualization_exercise.html
          - text: "Tidy Tuesday Exercise"
            href: ./tidytuesday_exercise.html
          - text: "Mini Data Analysis Exercise"
            href: ./datanalysis_exercise.html
          - text: "Tidy Tuesday 2 Exercise"
            href: ./tidytuesday_exercise2.html
      - text: "Flu Analysis"
        menu: 
          - text: "Wrangling"
            href: ./fluanalysis/code/processing_code.html
          - text: "Exploration"
            href: ./fluanalysis/code/exploration.html
          - text: "Fitting"
            href: ./fluanalysis/code/fitting.html
          - text: "Model Evaluation"
            href: ./fluanalysis/code/modeleval.html
          - text: "Machine Learning"
            href: ./fluanalysis/code/machinelearning.html
    right:
      - icon: github 
        href: https://github.com/bgeta/betelihemgetachew-MADA-portfolio2
        

format:
  html:
    theme: cosmo
    highlight: zenburn
    css: styles.css
    toc: FALSE


